# Exercices numpy

Dans ces exercices, il faut privilégier les solutions Numpy, plutôt que de les recoder en python. La solution tient généralement en une ligne 

In [2]:
import numpy as np

1. Créer et afficher un tableau numpy comprenant dans l'ordre les entiers de 10 à 59. Cf arange. 

In [3]:
import numpy as np
np.arange(10,60)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

2. Créer un tableau x et l'inverser. Utiliser le slicing 

In [4]:
import numpy as np
a = np.arange(0,20)
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

3. Créer un tableau 3*3 contenant les valeurs de 0 à 8. Cf reshape

In [5]:
a = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Créer un tableau 10*10 avec des valeurs aléatoires et trouver le minimum et le maximum. Cf random.random, min() et max()

6. Créer un tableau à 1 dimension et inverser tous les éléments dont la valeur est comprise entre 3 et 8 (inclus). Utiliser les opérateurs de comparaison et booléens entre tableaux 

In [6]:
x = np.arange(15)
x[(x > 3) & (x < 8)]*= - 1
print(x)



[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


8. Créer un tableau de 19 valeurs décimales aléatoires et remplacer le maximum par 0.   

In [57]:
a = np.random.rand(19)
b = np.array([0])
np.maximum(a,b)

array([0.56772226, 0.62589951, 0.62447776, 0.66632109, 0.75895262,
       0.33533275, 0.990722  , 0.27686818, 0.67231352, 0.92518507,
       0.18811933, 0.56887398, 0.94065383, 0.30545564, 0.51948158,
       0.4771645 , 0.57883864, 0.63693457, 0.16125481])

9. Créer un tableau avec des valeurs aléatoires. Soustraire à chaque case la moyenne du tableau. Utiliser le broadcasting. Vérifier que la moyenne du nouveau tableau ainsi obtenu est nulle

10. Créer un tableau 5*5 avec des valeurs aléatoires. Soustraire à chaque colonne sa moyenne. 

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [10]:
import numpy as np


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
import numpy as np
a = np.random.randint(1, 10000, size=100)
a.reshape(10,10)
np.min(a)
np.max(a)

222

In [30]:
import numpy as np
a = np.arange(0,9)
res = a[(a>3) & (a<8)]
res = np.flip(res,0)
print(res)

[7 6 5 4]
