# Mémento Numpy

## Numpy 3

- indexation intelligente (fancy indexing)
- tri

### fancy indexing

In [1]:
import numpy as np
x=np.arange(10)+3
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2]:
[x[3], x[7], x[2]]

[6, 10, 5]

In [3]:
ind = [3, 7, 2]
x[ind]

array([ 6, 10,  5])

Attention, la forme du tableau obtenu est celle du tableau des index, et pas celle du tableau initial :

In [4]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[ 6, 10],
       [ 7,  8]])

On peut utiliser le fancy indexing avec des tableau multi indices

In [5]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

### Tri

Tri d'un tableau mono-indice

In [7]:
x=np.array([3,5,6,2,9])
np.sort(x)

array([2, 3, 5, 6, 9])

In [8]:
np.argsort(x)

array([3, 0, 1, 2, 4], dtype=int64)

Tri d'un tableau multi indice. Chaque ligne (ou colonne) est triée independemment des autres

In [9]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [10]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [11]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Partitionnement