# Mémento Numpy

## Numpy 1

- Attributs d'un tableau
- Indexation des éléments d'un tableau
- Slicing : indexation de sous tableaux
- Reshaping de tableau
- Concaténation de tableaux
- Split de tableaux


Pour plus de détails : 
- la liste des fonctions  https://docs.scipy.org/doc/numpy-1.13.0/reference/ 
- le guide de l'utilisateur https://docs.scipy.org/doc/numpy-1.13.0/user/index.html#user


### Attributs d'un tableau

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32


### Indexation des éléments d'un tableau

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x1[0]

5

In [4]:
x1[-1]

9

### Slicing : indexation de sous tableaux

La syntaxe est celle des boucles for : x[start:stop:step]
L'index stop est toujours exclus. Les valeurs par défaut sont 0 pour start, len(x) pour stop, 1 pour step

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(x[:5]) 
print(x[5:]) 
print(x[4:7]) 
print(x[::2]) 
print(x[1::2])


[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]


Quand step<0, les valeurs start et stop sont permutées

In [7]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [8]:
print(x[5::-2])

[5 3 1]


Pour les tableaux multi indices, le principe est le même

In [9]:
print(x2)
print(x2[:2,:3])
print(x2[:2,::2])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]
[[3 2]
 [7 8]]


Pour récupérer les tableaux colonnes ou lignes : 

In [10]:
print(x2[:, 0])
print(x2[0, :])

[3 7 1]
[3 5 2 4]


Remarque : quand on modifie une slice de tableau, on modifie également le tableau initial (vérifiez-le!). On aura parfois besoin de copier les tableau :

In [11]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 5]
 [7 6]]


### Reshaping de tableau

In [12]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
x = np.array([1, 2, 3])

# 2 solutions pour obtenir une dimension supplémentaire
print(x.reshape((1, 3)))
print(x[np.newaxis, :])

[[1 2 3]]
[[1 2 3]]


### Concaténation de tableaux

In [14]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [15]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


Pour les tableaux multi indices, on précise l'axe dimension qui supporte le "collage" (0 par défaut):

In [16]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [17]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Si la dimension des tableaux n'est pas la même, on utilise :

In [18]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [19]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Split de tableaux

voir les fonctions np.split, np.hsplit et np.vsplit.